Speaker and Gender Recognition Phase 3
- Hayat Awais Malik (21100016)
- Muhammad Junaid (21100025)
- Muhammad Sabeeh Rehman (21100186)
- Muhammad Shehryaar Sharif (21100146)
- Rabeeya Hamid (21100105)

In [1]:
!pip install python_speech_features

In [2]:
import python_speech_features as mfcc
from scipy.io.wavfile import read
import numpy as np
import os
import matplotlib.pyplot as plt
import time
from tqdm.notebook import tqdm
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [3]:
!gdown --id 18qSvsM5W2QFASUlLWFPqxuYFPZcOs25b

Downloading...
From: https://drive.google.com/uc?id=18qSvsM5W2QFASUlLWFPqxuYFPZcOs25b
To: /content/LUMS_FALL2020_PROJECT_DATA1.zip
802MB [00:05, 139MB/s]


In [4]:
!unzip /content/LUMS_FALL2020_PROJECT_DATA1.zip -d /content/dataset_project

Archive:  /content/LUMS_FALL2020_PROJECT_DATA1.zip
replace /content/dataset_project/Gender_Recognition/Test/SPK083_M/1.wav? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/1.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/10.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/2.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/3.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/4.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/5.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/6.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/7.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/8.wav  
  inflating: /content/dataset_project/Gender_Recognition/Test/SPK083_M/9.wav  
  inflating: /content/dataset_project/Gender_

# File Reading & Feature Extraction

In [5]:
def get_MFCC(audio, sr):
    features = mfcc.mfcc(audio, sr, 0.025, 0.01, 13, appendEnergy = True)
    return np.mean(features, axis=0)

In [6]:
Gender_Recognition_path='/content/dataset_project/Gender_Recognition/'
Speaker_Recognition_path='/content/dataset_project/Speaker_Recognition/'

Train_data_GR=[]
Test_data_GR=[]


Train_labels_GR=[]
Test_labels_GR=[]

Train_data_SR=[]
Test_data_SR=[]

Train_labels_SR=[]
Test_labels_SR=[]

Data_types_GR = os.listdir(Gender_Recognition_path)
Data_types_SR = os.listdir(Speaker_Recognition_path)


train_folder_GR=os.listdir(Gender_Recognition_path+"/"+Data_types_GR[1])
test_folder_GR=os.listdir(Gender_Recognition_path+"/"+Data_types_GR[0])

train_folder_SR=os.listdir(Speaker_Recognition_path+"/"+Data_types_SR[1])
test_folder_SR=os.listdir(Speaker_Recognition_path+"/"+Data_types_SR[0])



#training features for Gender Recognition
for folder in train_folder_GR:
  # print(folder[-1])
  if folder[-1] =="M":
    [Train_labels_GR.append(0) for i in range(10)]
  else:
    [Train_labels_GR.append(1) for i in range(10)]
  
  vn_folder=os.listdir(Gender_Recognition_path+"/"+Data_types_GR[1]+"/"+folder)
  for vn in vn_folder:
    sr, audio = read(Gender_Recognition_path+"/"+Data_types_GR[1]+"/"+folder+"/"+vn)
    features = get_MFCC(audio, sr)
    # print (features.shape)
    Train_data_GR.append(features)

#testing features for Gender Recognition
for folder in test_folder_GR:
  if folder[-1] =="M":
    [Test_labels_GR.append(0) for i in range(10)]
  else:
    [Test_labels_GR.append(1) for i in range(10)]
    
  vn_folder=os.listdir(Gender_Recognition_path+"/"+Data_types_GR[0]+"/"+folder)
  for vn in vn_folder:
    sr, audio = read(Gender_Recognition_path+"/"+Data_types_GR[0]+"/"+folder+"/"+vn)
    features = get_MFCC(audio, sr)
    # print (features.shape)
    Test_data_GR.append(features)




#training features for Speaker Recognition
for folder in train_folder_SR:
  [Train_labels_SR.append(int(folder[3:6]) - 1) for i in range(8)]
  vn_folder=os.listdir(Speaker_Recognition_path+"/"+Data_types_SR[1]+"/"+folder)
  for vn in vn_folder:
    sr, audio = read(Speaker_Recognition_path+"/"+Data_types_SR[1]+"/"+folder+"/"+vn)
    features = get_MFCC(audio, sr)
    # print (features.shape)
    Train_data_SR.append(features)

#testing features for Speaker Recognition
for folder in test_folder_SR:
  [Test_labels_SR.append(int(folder[3:6]) - 1) for i in range(2)]
  vn_folder=os.listdir(Speaker_Recognition_path+"/"+Data_types_SR[0]+"/"+folder)
  for vn in vn_folder:
    sr, audio = read(Speaker_Recognition_path+"/"+Data_types_SR[0]+"/"+folder+"/"+vn)
    features = get_MFCC(audio, sr)
    # print (features.shape)
    Test_data_SR.append(features)



Train_data_GR=np.array(Train_data_GR)
Train_data_SR=np.array(Train_data_SR)

Test_data_GR=np.array(Test_data_GR)
Test_data_SR=np.array(Test_data_SR)



Train_labels_GR=np.array(Train_labels_GR)
Train_labels_SR=np.array(Train_labels_SR)

Test_labels_GR=np.array(Test_labels_GR)
Test_labels_SR=np.array(Test_labels_SR)


In [7]:
print(Test_labels_GR.shape)
print(Train_labels_GR.shape)
print(Test_labels_SR.shape)
print(Train_labels_SR.shape)
print(Test_data_GR.shape)
print(Train_data_GR.shape)
print(Test_data_SR.shape)
print(Train_data_SR.shape)

(170,)
(1250,)
(284,)
(1136,)
(170, 13)
(1250, 13)
(284, 13)
(1136, 13)


# Part 1

## Gender Recognition

### Hyper-parameter Tuning Using Grid Search

In [8]:
# parameters = {'solver': ['sgd'], 'max_iter': [5000], "activation": ["logistic"], 'hidden_layer_sizes': [(128,64), (64),(64,32), (32)], 'random_state':[1], "learning_rate_init": [0.1, 0.4, 0.01]}


MLP = MLPClassifier(random_state=1, max_iter=5000, activation="logistic", solver="sgd")
tuned_params={"learning_rate_init": [0.4, 0.1, 0.01], 'hidden_layer_sizes': [(128,64),(64,1),(64,32),(32,1)]}

clf_GR = GridSearchCV(MLP, tuned_params, scoring="f1_macro",verbose=1)
clf_GR.fit(Train_data_GR,Train_labels_GR)
print(clf_GR.best_params_)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed:  1.6min finished


{'hidden_layer_sizes': (64, 32), 'learning_rate_init': 0.01}


In [9]:
predictions=clf_GR.predict(Test_data_GR)

### Evaluation

In [10]:
print(classification_report(Test_labels_GR,predictions))
print(accuracy_score(Test_labels_GR,predictions))
print(confusion_matrix(Test_labels_GR,predictions))

              precision    recall  f1-score   support

           0       0.90      0.92      0.91       130
           1       0.71      0.68      0.69        40

    accuracy                           0.86       170
   macro avg       0.81      0.80      0.80       170
weighted avg       0.86      0.86      0.86       170

0.8588235294117647
[[119  11]
 [ 13  27]]


Additional Evaluation

In [11]:
print("82% f1-macro achieved at LR = 0.005 and Hidden_Layers = (128, 64)")

82% f1-macro achieved at LR = 0.005 and Hidden_Layers = (128, 64)


## Speaker Recognition

### Hyper-parameter Tuning Using Grid Search

In [12]:
clf_SR = GridSearchCV(MLP, tuned_params, scoring="f1_macro",verbose=1)
clf_SR.fit(Train_data_SR,Train_labels_SR)
print(clf_SR.best_params_)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed: 16.8min finished


{'hidden_layer_sizes': (128, 64), 'learning_rate_init': 0.1}


In [13]:
predictions=clf_SR.predict(Test_data_SR)

### Evaluation

In [14]:
print(classification_report(Test_labels_SR,predictions))
print(accuracy_score(Test_labels_SR,predictions))
print(confusion_matrix(Test_labels_SR,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         2
           7       0.67      1.00      0.80         2
           8       1.00      1.00      1.00         2
           9       1.00      1.00      1.00         2
          10       1.00      1.00      1.00         2
          11       1.00      1.00      1.00         2
          12       1.00      1.00      1.00         2
          13       1.00      1.00      1.00         2
          14       1.00      1.00      1.00         2
          15       1.00      1.00      1.00         2
          16       1.00      1.00      1.00         2
          17       1.00    

## Part 2
Linear SVM

In [15]:
def LinearSVM(trainX, testX, trainLabels):
  LSV = svm.LinearSVC(random_state=1, max_iter=5000, dual=False)
  LSV.fit(trainX, trainLabels)
  return LSV.predict(testX)

LSV_predictions_GR = LinearSVM(Train_data_GR, Test_data_GR, Train_labels_GR)
LSV_predictions_SR = LinearSVM(Train_data_SR, Test_data_SR, Train_labels_SR)

### Gender Recognition

In [16]:
print("Accuracy on test GR:",accuracy_score(Test_labels_GR, LSV_predictions_GR))
print("================= {} ==================".format("GR Report on test data"))
print(classification_report(Test_labels_GR, LSV_predictions_GR))
print("================= {} ==================".format("Confusion Matrix"))
print(confusion_matrix(Test_labels_GR, LSV_predictions_GR))

Accuracy on test GR: 0.8352941176470589
================= GR Report on test data ==================
              precision    recall  f1-score   support

           0       0.87      0.92      0.90       130
           1       0.69      0.55      0.61        40

    accuracy                           0.84       170
   macro avg       0.78      0.74      0.75       170
weighted avg       0.83      0.84      0.83       170

================= Confusion Matrix ==================
[[120  10]
 [ 18  22]]


### Speaker Recognition

In [17]:
print("Accuracy on test SR:",accuracy_score(Test_labels_SR, LSV_predictions_SR))
print("================= {} ==================".format("SR Report on test data"))
print(classification_report(Test_labels_SR, LSV_predictions_SR))
print("================= {} ==================".format("Confusion Matrix"))
print(confusion_matrix(Test_labels_SR, LSV_predictions_SR))

Accuracy on test SR: 0.8415492957746479
================= SR Report on test data ==================
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         2
           3       0.00      0.00      0.00         2
           4       1.00      1.00      1.00         2
           5       0.67      1.00      0.80         2
           6       0.33      1.00      0.50         2
           7       0.50      0.50      0.50         2
           8       0.50      1.00      0.67         2
           9       1.00      1.00      1.00         2
          10       1.00      1.00      1.00         2
          11       1.00      0.50      0.67         2
          12       0.67      1.00      0.80         2
          13       0.67      1.00      0.80         2
          14       1.00      1.00      1.00         2
          15       1.00      1.00  

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Part 3
Naive Bayes

In [18]:
def NaiveBayes(trainX, testX, trainLabels):
  NB = GaussianNB()
  NB.fit(trainX, trainLabels)
  return NB.predict(testX)  

NB_predictions_GR = NaiveBayes(Train_data_GR, Test_data_GR, Train_labels_GR)
NB_predictions_SR = NaiveBayes(Train_data_SR, Test_data_SR, Train_labels_SR)

### Gender Recognition

In [19]:
print("Accuracy on test GR:",accuracy_score(Test_labels_GR, NB_predictions_GR))
print("================= {} ==================".format("SR Report on test data"))
print(classification_report(Test_labels_GR, NB_predictions_GR))
print("================= {} ==================".format("Confusion Matrix"))
print(confusion_matrix(Test_labels_GR, NB_predictions_GR))

Accuracy on test GR: 0.8529411764705882
================= SR Report on test data ==================
              precision    recall  f1-score   support

           0       0.89      0.92      0.91       130
           1       0.71      0.62      0.67        40

    accuracy                           0.85       170
   macro avg       0.80      0.77      0.79       170
weighted avg       0.85      0.85      0.85       170

================= Confusion Matrix ==================
[[120  10]
 [ 15  25]]


### Speaker Recognition

In [20]:
print("Accuracy on test SR:",accuracy_score(Test_labels_SR, NB_predictions_SR))
print("================= {} ==================".format("SR Report on test data"))
print(classification_report(Test_labels_SR, NB_predictions_SR))
print("================= {} ==================".format("Confusion Matrix"))
print(confusion_matrix(Test_labels_SR, NB_predictions_SR))

Accuracy on test SR: 0.9225352112676056
================= SR Report on test data ==================
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         2
           8       1.00      1.00      1.00         2
           9       1.00      1.00      1.00         2
          10       1.00      1.00      1.00         2
          11       1.00      1.00      1.00         2
          12       1.00      1.00      1.00         2
          13       1.00      1.00      1.00         2
          14       1.00      1.00      1.00         2
          15       1.00      1.00  

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
